#vivado 2024.1
# Sistema Embebido Multijugador (Pong) — Nexys A7-100T
# EL3313 Taller de Diseno Digital, I Semestre 2026

[main]
PART = xc7a100tcsg324-1
BOARD = digilentinc.com:nexys-a7-100t:part0:1.3

[impl_1]
STEPS.PHYS_OPT_DESIGN.IS_ENABLED = 1
STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE = 1

[hog]
ALLOW_FAIL_ON_GIT = False
ALLOW_FAIL_ON_LIST = False
ALLOW_FAIL_ON_CONF = False
